### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by OMGtechy** [BaseMax/FirstAssemblyWindows#1]
You may be interested in https://github.com/OMGtechy/tinydoze
I got it smaller than Dave did ;)

**Comment by BaseMax** [comment]
Hi Artemis, Thank you for your message. @OMGtechy 

It's awesome. You breached the limitation and did it in such a way that still works.

**Comment by BaseMax** [comment]
I like the ideas which you wrote on README. If it's okay for you. I would like to add your project as a showcase in README for ASM lovers. We support others and yes it's how open-source works.

**Comment by BaseMax** [comment]
Feel free to update/edit/remove it anytime you want by sending a PR.
Happy connecting ^_^

**Comment by OMGtechy** [comment]
> I like the ideas which you wrote on README. If it's okay for you. I would like to add your project as a showcase in README for ASM lovers. We support others and yes it's how open-source works.

Sure thing!
